"""empty message

Revision ID: 0766542b4423
Revises: 
Create Date: 2022-08-02 04:02:58.209706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0766542b4423'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.String(), nullable=True))
    # ### end Alembic commands ###

     # this is to accommodate already existing table so it run
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos','completed', nullable=False)
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
